language: php
php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   name: Lowest Dependencies
            install:
                - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable


        -   name: Nette Code Checker
            install:
                - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
            script:
                - php temp/code-checker/code-checker --strict-types


        -   name: Nette Coding Standard
            install:
                - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
            script:
                - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.yml


        -   stage: Static Analysis (informative)
            install:
                # Install PHPStan
                - travis_retry composer create-project phpstan/phpstan-shim temp/phpstan --no-progress
                - travis_retry composer install --no-progress --prefer-dist
            script:
                - php temp/phpstan/phpstan.phar analyse --autoload-file vendor/autoload.php --level 5 src


        -   stage: Code Coverage
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


    allow_failures:
        -   stage: Static Analysis (informative)
        -   stage: Code Coverage


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
