language: php
php:
    - 7.0
    - 7.1

env:
matrix:
    include:
        - php: 7.0
          env: dependencies="--prefer-lowest --prefer-stable"
        - php: 7.0
          env: coverage=on

    allow_failures:
        - php: 7.0
          env: coverage=on

script:
    - vendor/bin/tester tests -s $coverageArgs
    - php temp/code-checker/src/code-checker.php --short-arrays

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer update --no-interaction --prefer-dist $dependencies
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.5 --no-interaction
    - if [ "$coverage" == "on" ]; then coverageArgs="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
