name: Coding Style

on: [push, pull_request]

jobs:
    nette_cc:
        name: Nette Code Checker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: 7.2
                  coverage: none

            - run: composer create-project nette/code-checker temp/code-checker ^3 --no-progress
            - run: php temp/code-checker/code-checker --strict-types --no-progress


    nette_cs:
        name: Nette Coding Standard
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v1
              with:
                  php-version: 8.0
                  coverage: none

            - run: composer create-project nette/coding-standard temp/coding-standard ^3 --no-progress --ignore-platform-reqs
            - run: php temp/coding-standard/ecs check
